name: Update Sphinx

on: [push]

jobs:
  updateBranch:
    name: Update staging branch
    runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@master
    #   - uses: Embraser01/update-git-branch-action@v1.0.0
    #     if: github.ref == 'refs/heads/master'
    #     with:
    #       branch: gh-pages
    #       githubToken: ${{ secrets.DOC_TOKEN }} # Github Token
    steps:
      - run:
        bash scripts/build_docs.sh
      # - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # - run: echo "there is a TOKEN -> ${{secrets.GITHUB_TOKEN}}"

      # - name: Check out repository code
      #   uses: actions/checkout@v2
      #   with:
      #     token: ${{secrets.GITHUB_TOKEN}}

      # - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "The workflow is now ready to test your code on the runner."
      # - uses: actions/checkout@v2
      # - name: Set Git config
      #   run: |
      #     git config --local user.email "paulogil2010@github.com"
      #     git config --local user.name "Paulo Lenz"

      # - name: Pull from master
      #   run: |
      #     git fetch --unshallow
      #     git checkout gh-pages
      #     git pull origin master

      # - run: echo "Change to ${{ github.ref }} branch"

      # - name: install packages
      #   run: |
      #     echo "Trying to install packages"
      #     cd backend/
      #     echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      #     ls -lha
      #     python3 -m pip install backend/requirements-doc.txt

      # - name: install packages
      #   run: |
      #     echo "Trying to run make"
      #     cd docsrc/
      #     pwd
      #     make github
      #     cd ../../
      #     pwd
      #     cp -a backend/docsrc/html/* docs/
      #     ls -l docs/
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}

      # - name: Pushing to gh-pages
      #   run: |
      #     git add .
      #     git commit -m "docs: add docs from GitHub Pages"
      # - run: echo "🍏 This job's status is ${{ job.status }}."
