name: Sphinx Pages

on: push
# on: pull_request

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  main:
    name: Build gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: config git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git config pull.rebase false

      - name: check git
        run: |
          git remote show origin -n
          git fetch
          git fetch --prune

      - name: change to gh-pages
        run: |
          git checkout "gh-pages"
          git pull origin gh-pages
          git branch --show-current

      - name: update from main
        run: |
          git pull origin "$DEFAULT_BRANCH"
          git status

      - name: generates docs
        run: |
          cd backend/
          pip install -r requirements-doc.txt
          cd docsrc/
          sphinx-apidoc \
            --separate \
            --force \
            --ext-autodoc \
            --ext-doctest \
            --ext-intersphinx \
            --ext-todo \
            --ext-coverage \
            --ext-imgmath \
            --ext-mathjax \
            --ext-ifconfig \
            --ext-viewcode \
            --ext-githubpages \
            -o source/backend .. ../../backend \
              ../*/migrations \
              ../*/tests
          make clean
          make github

      - name: Commit files
        run: |
          date > gh-action.log
          git add .
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
