name: Update Sphinx

on: push

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  GITHUB_TOKEN: ${{ secrets.DOC_TOKEN }}

jobs:
  main:
    name: Merge Main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: config git
        run: |
          git config --global user.email "paulogil2010@gmail.com"
          git config --global user.name "GitHub Actions"
          git config pull.rebase false

      - name: update branches
        run: |
          git fetch
          git fetch --prune
          git branch -a

      - name: checking steps
        run: |
          git branch --show-current
          git status

      - name: change to gh-pages
        run: |
          git checkout "gh-pages"
          git pull origin gh-pages
          git branch --show-current

      - name: update from test
        run: |
          git pull origin test
          git status

      - name: Create file
        run: |
          touch 'file.txt'
          git status

      - name: add commit and push
        run: |
          git branch --show-current

          git add .
          git commit -m 'add file.txt'
          git push
          git status
